<svelte:head>
  <title>Privacy Policy | Blulux Shop</title>
</svelte:head>

<div class="container">
  <h2>EFFECTIVE DATE: JUNE 22, 2021</h2>
  <p>
    Bluluxshop, LTD. ("us", "we", or "our") operates the <a
      href="https://bluluxshop.com">https://bluluxshop.com</a
    >
    website (the "Service").
  </p>
  <p>
    This page informs you of our policies regarding the collection, use, and
    disclosure of personal data when you use our Service and the choices you
    have associated with that data.
  </p>
  <p>
    We use your data to provide and improve the Service. By using the Service,
    you agree to the collection and use of information in accordance with this
    policy. Unless otherwise defined in this Privacy Policy, terms used in this
    Privacy Policy have the same meanings as in our Terms and Conditions,
    accessible from  <a href="https://bluluxshop.com">https://bluluxshop.com</a>
  </p>
  <div>
    <h2>DEFINITIONS</h2>
    <ul>
      <li>
        SERVICEService is the <a href="https://bluluxshop.com"
          >https://bluluxshop.com</a
        >  website operated by Bluluxshop, LTD.
      </li>
      <li>
        PERSONAL DATAPersonal Data means data about a living individual who can
        be identified from those data (or from those and other information
        either in our possession or likely to come into our possession)
      </li>
      <li>
        USAGE DATAUsage Data is data collected automatically either generated by
        the use of the Service or from the Service infrastructure itself (for
        example, the duration of a page visit).
      </li>
      <li>
        COOKIESCookies are small pieces of data stored on your device (computer
        or mobile device).
      </li>
    </ul>
  </div>
  <div>
    <h2>INFORMATION COLLECTION AND USE</h2>
    <p>
      We collect several different types of information for various purposes to
      provide and improve our Service to you.
    </p>
  </div>
  <h2>TYPES OF DATA COLLECTED</h2>
  <h3>PERSONAL DATA</h3>
  <p>
    While using our Service, we may ask you to provide us with certain
    personally identifiable information that can be used to contact or identify
    you ("Personal Data"). Personally identifiable information may include, but
    is not limited to:
  </p>
  <ul>
    <li>Email address</li>
    <li>First name and last name</li>
    <li>Phone number</li>
    <li>Address, State, Province, ZIP/Postal code, City</li>
    <li>Cookies and Usage Data</li>
  </ul>
  <p>
    We may use your Personal Data to contact you with newsletters, marketing or
    promotional materials and other information that may be of interest to you.
    You may opt out of receiving any, or all, of these communications from us by
    following the unsubscribe link or instructions provided in any email we
    send.
  </p>
  <div>
    <h3>USAGE DATA</h3>
    <p>
      We may also collect information how the Service is accessed and used
      ("Usage Data"). This Usage Data may include information such as your
      computer's Internet Protocol address (e.g. IP address), browser type,
      browser version, the pages of our Service that you visit, the time and
      date of your visit, the time spent on those pages, unique device
      identifiers and other diagnostic data.
    </p>
  </div>
  <div>
    <h3>LOCATION DATA</h3>
    <p>
      We may use and store information about your location if you give us
      permission to do so (“Location Data”). We use this data to provide
      features of our Service, to improve and customize our Service. You can
      enable or disable location services when you use our Service at any time,
      through your device settings.
    </p>
  </div>
  <div>
    <h3>TRACKING & COOKIES DATA</h3>
    <p>
      We use cookies and similar tracking technologies to track the activity on
      our Service and hold certain information.
    </p>
    <p>
      Cookies are files with small amount of data which may include an anonymous
      unique identifier. Cookies are sent to your browser from a website and
      stored on your device. Tracking technologies also used are beacons, tags,
      and scripts to collect and track information and to improve and analyze
      our Service.
    </p>
    <p>
      You can instruct your browser to refuse all cookies or to indicate when a
      cookie is being sent. However, if you do not accept cookies, you may not
      be able to use some portions of our Service.
    </p>
    <p>Examples of Cookies we use:</p>
    <ul>
      <li>Session Cookies. We use Session Cookies to operate our Service.</li>
      <li>
        Preference Cookies. We use Preference Cookies to remember your
        preferences and various settings.
      </li>
      <li>Security Cookies. We use Security Cookies for security purposes.</li>
    </ul>
  </div>
  <div>
    <h2>USE OF DATA</h2>
    <p>Bluluxshop, LTD. uses the collected data for various purposes:</p>
    <ul>
      <li>To provide and maintain our Service</li>
      <li>To notify you about changes to our Service</li>
      <li>
        To allow you to participate in interactive features of our Service when
        you choose to do so
      </li>
      <li>To provide customer support</li>
      <li>
        To gather analysis or valuable information so that we can improve our
        Service
      </li>
      <li>To monitor the usage of our Service</li>
      <li>To detect, prevent and address technical</li>
      <li>
        To provide you with news, special offers and general information about
        other goods, services and events which we offer that are similar to
        those that you have already purchased or enquired about unless you have
        opted not to receive such information
      </li>
    </ul>
  </div>
  <div>
    <h2>TRANSFER OF DATA</h2>
    <p>
      Your information, including Personal Data, may be transferred to — and
      maintained on —computers located outside of your state, province, country
      or other governmental jurisdiction where the data protection laws may
      differ than those from your jurisdiction.
    </p>
    <p>
      If you are located outside the United Kingdom and choose to provide
      information to us, please note that we transfer the data, including
      Personal Data, to the United Kingdom and process it there.
    </p>
    <p>
      Your consent to this Privacy Policy followed by your submission of such
      information represents your agreement to that transfer. Bluluxshop, LTD.
      will take all steps reasonably necessary to ensure that your data is
      treated securely and in accordance with this Privacy Policy and no
      transfer of your Personal Data will take place to an organization or a
      country unless there are adequate controls in place including the security
      of your data and other personal information.
    </p>
  </div>
  <h2>DISCLOSURE OF DATA</h2>
  <div>
    <h3>DISCLOSURE FOR LAW ENFORCEMENT</h3>
    <p>
      Under certain circumstances, Bluluxshop, LTD. may be required to disclose
      your Personal Data if required to do so by law or in response to valid
      requests by public authorities (e.g. a court or a government agency).
    </p>
  </div>
  <div>
    <h3>LEGAL REQUIREMENTS</h3>
    <p>
      Bluluxshop LTD. may disclose your Personal Data in the good faith belief
      that such action is necessary to:
    </p>
    <ul>
      <li>To comply with a legal obligation</li>
      <li>To protect and defend the rights or operty of Bluluxshop, LTD.</li>
      <li>
        To prevent or investigate possible wrongdoing in connection with the
        Service
      </li>
      <li>
        To protect the personal safety of users of the Service or the public
      </li>
      <li>To protect against legal liability</li>
    </ul>
  </div>
  <div>
    <h2>SECURITY OF DATA</h2>
    <p>
      The security of your data is important to us, but remember that no method
      of transmission over the Internet, or method of electronic storage is 100%
      secure. While we strive to use commercially acceptable means to protect
      your Personal Data, we cannot guarantee its absolute security.
    </p>
  </div>
  <div>
    <h2>SERVICE PROVIDERS</h2>
    <p>
      We may employ third party companies and individuals to facilitate our
      Service ("Service Providers"), to provide the Service on our behalf, to
      perform Service-related services or to assist us in analyzing how our
      Service is used. These third parties have access to your Personal Data
      only to perform these tasks on our behalf and are obligated not to
      disclose or use it for any other purpose.
    </p>
  </div>
  <div>
    <h2>ANALYTICS</h2>
    <p>
      We may use third-party Service Providers to monitor and analyze the use of
      our Service.
    </p>
    <ol>
      <li>
        <p>
          Google Analytics is a web analytics service offered by Google that
          tracks and reports website traffic.
        </p>

        <p>
          Google uses the data collected to track and monitor the use of our
          Service. This data is shared with other Google services.
        </p>

        <p>
          Google may use the collected data to contextualize and personalize the
          ads of its own advertising network.
        </p>
        <p>
          You can opt-out of having made your activity on the Service available
          to Google Analytics by installing the Google Analytics opt-out browser
          add-on. The add-on prevents the Google Analytics JavaScript (ga.js,
          analytics.js, and dc.js) from sharing information with Google
          Analytics about visits activity.
        </p>
        <p>
          For more information on the privacy practices of Google, please visit
          the Google Privacy & Terms web page: <a
            href="https://policies.google.com/privacy?hl=en"
            rel="noreferrer"
            target="_blank"
          >
            Link</a
          >
        </p>
      </li>
    </ol>
  </div>
  <div>
    <h2>BEHAVIORAL REMARKETING</h2>
    <p>
      Bluluxshop, LTD. uses remarketing services to advertise on third party
      websites to you after you visited our Service. We and our third-party
      vendors use cookies to inform, optimize and serve ads based on your past
      visits to our Service.
    </p>
    <ol>
      <li>
        <p>Google AdWords remarketing service is provided by Google Inc.</p>
        <p>
          You can opt-out of Google Analytics for Display Advertising and
          customize the Google Display Network ads by visiting the Google Ads
          Settings page: <a
            href="http://www.google.com/settings/ads"
            rel="noreferrer"
            target="_blank">Link</a
          >
        </p>
        <p>
          Google also recommends installing the Google Analytics Opt-out Browser
          Add-on - <a
            href="https://tools.google.com/dlpage/gaoptout"
            rel="noreferrer"
            target="_blank">Link</a
          > - for your web browser. Google Analytics Opt-out Browser Add-on
          provides visitors with the ability to prevent their data from being
          collected and used by Google Analytics.
        </p>
        <p>
          For more information on the privacy practices of Google, please visit
          the Google Privacy & Terms web page: <a
            href="https://policies.google.com/privacy?hl=en"
            rel="noreferrer"
            target="_blank">Link</a
          >
        </p>
      </li>
      <li>
        <p>Facebook remarketing service is provided by Facebook Inc.</p>
        <p>
          You can learn more about interest- based advertising from Facebook by
          visiting this page: <a
            href="https://www.facebook.com/help/1649686"
            rel="noreferrer"
            target="_blank">Link</a
          >
        </p>

        <p>
          To opt-out from Facebook's interest- based ads follow these
          instructions from Facebook: <a
            href="https://www.facebook.com/help/5681374"
            rel="noreferrer"
            target="_blank">Link</a
          >
        </p>

        <p>
          Facebook adheres to the Self-Regulatory Principles for Online
          Behavioral Advertising established by the Digital Advertising
          Alliance.
        </p>

        <p>
          You can also opt-out from Facebook and other participating companies
          through the Digital Advertising Alliance in the USA <a
            href="https://www.aboutads.info/choices"
            rel="noreferrer"
            target="_blank">http://www.aboutads.info/choices/</a
          >, the Digital Advertising Alliance of Canada in Canada
          <a href="https://youradchoices.ca/" rel="noreferrer" target="_blank"
            >https://youradchoices.ca/</a
          >
          or the European Interactive Digital Advertising Alliance in Europe
          <a
            href="https://www.youronlinechoices.eu"
            rel="noreferrer"
            target="_blank">https://www.youronlinechoices.eu/</a
          >, or opt-out using your mobile device settings.
        </p>
        <p>
          For more information on the privacy practices of Facebook, please
          visit Facebook's Data Policy: <a
            href="https://www.facebook.com/privacy/explain"
            rel="noreferrer"
            target="_blank">Link</a
          >
        </p>
      </li>
    </ol>
  </div>
  <div>
    <h2>PAYMENTS</h2>
    <p>
      We may provide paid products and/or services within the Service. In that
      case, we use third-party services for payment processing (e.g. payment
      processors).
    </p>
    <p>
      We will not store or collect your payment card details. That information
      is provided directly to our third-party payment processors whose use of
      your personal information is governed by their Privacy Policy. These
      payment processors adhere to the standards set by PCI-DSS as managed by
      the PCI Security Standards Council, which is a joint effort of brands like
      Visa, Mastercard, American Express and Discover. PCI-DSS requirements help
      ensure the secure handling of payment information.
    </p>
    <ol>
      <li>
        <p>
          STRIPE.COM Their Privacy Policy can be viewed at <a
            href="https://stripe.com/privacy"
            rel="noreferrer"
            target="_blank">https://stripe.com/privacy</a
          >
        </p>
      </li>
    </ol>
  </div>
  <div>
    <h2>LINKS TO OTHER SITES</h2>
    <p>
      Our Service may contain links to other sites that are not operated by us.
      If you click on a third party link, you will be directed to that third
      party's site. We strongly advise you to review the Privacy Policy of every
      site you visit.
    </p>
    <p>
      We have no control over and assume no responsibility for the content,
      privacy policies or practices of any third party sites or services.
    </p>
  </div>
  <div>
    <h2>CHILDREN'S PRIVACY</h2>
    <p>Our Service does not address anyone under the age of 18 ("Children").</p>
    <p>
      We do not knowingly collect personally identifiable information from
      anyone under the age of 18. If you are a parent or guardian and you are
      aware that your child has provided us with Personal Data, please contact
      us. If we become aware that we have collected Personal Data from children
      without verification of parental consent, we take steps to remove that
      information from our servers.
    </p>
  </div>
  <div>
    <h2>CHANGES TO THIS PRIVACY POLICY</h2>
    <p>
      We may update our Privacy Policy from time to time. We will notify you of
      any changes by posting the new Privacy Policy on this page.
    </p>
    <p>
      We will let you know via email and/or a prominent notice on our Service,
      prior to the change becoming effective and update the "effective date" at
      the top of this Privacy Policy.
    </p>
    <p>
      You are advised to review this Privacy Policy periodically for any
      changes. Changes to this Privacy Policy are effective when they are posted
      on this page.
    </p>
  </div>
  <div>
    <h2>CONTACT US</h2>
    <p>
      If you have any questions about this Privacy Policy, please contact us:<br
      />
      By email:
      <a href="mailto:bluluxgelsystem@gmail.com">bluluxgelsystem@gmail.com</a>
    </p>
  </div>
</div>

<style>
  .container {
    max-width: 1024px;
    margin: 0 auto;
    text-align: center;
    padding: 1rem;
    padding-bottom: 10rem;
  }

  h2 {
    font-size: 2rem;
    padding: 1rem 0;
  }

  h3 {
    font-size: 1.6rem;
    padding: 0.6rem 0;
  }

  p {
    text-align: left;
    padding-bottom: 1rem;
    font-size: 1.2rem;
    line-height: 1.4;
  }

  a {
    color: var(--brand-dark);
  }
  a:hover {
    text-decoration: underline;
  }

  ol,
  ul {
    padding-bottom: 1rem;
    padding-left: 1.5rem;
    text-align: left;
  }

  ol {
    list-style-type: decimal;
  }

  ul {
    list-style-type: disc;
  }

  li {
    padding-bottom: 0.5rem;
    font-size: 1.1rem;
  }

  li > p {
    font-size: 1.1rem;
    padding-bottom: 0.5rem;
  }
</style>
